name: FireballPlugin
version: 1.0
main: com.example.fireballplugin.FireballPlugin
api-version: '1.21'
description: 一個允許玩家投擲火球的插件
author: YourName
website: https://github.com/yourusername/FireballPlugin

commands:
  fireball:
    description: 發射一個火球或管理火焰彈功能
    usage: |
      &c用法:
      &f/fireball &7- 發射一個火球
      &f/fireball toggle &7- 切換火焰彈功能開關
      &f/fireball on &7- 啟用火焰彈功能
      &f/fireball off &7- 禁用火焰彈功能
      &f/fireball status &7- 查看火焰彈功能狀態
      &f/fireball reload &7- 重新載入插件配置
    permission: fireballplugin.use
    aliases: [fb, fireballplugin]
    
permissions:
  fireballplugin.use:
    description: 允許玩家使用火球指令
    default: op
  fireballplugin.toggle:
    description: 允許玩家切換火焰彈功能開關
    default: op
  fireballplugin.status:
    description: 允許玩家查看火焰彈功能狀態
    default: op
  fireballplugin.reload:
    description: 允許玩家重新載入插件配置
    default: op
  fireballplugin.rightclick:
    description: 允許玩家通過右鍵點擊發射火球
    default: op
  fireballplugin.*:
    description: 允許使用所有火焰彈插件功能
    default: op
    children:
      fireballplugin.use: true
      fireballplugin.toggle: true
      fireballplugin.status: true
      fireballplugin.reload: true
      fireballplugin.rightclick: true